Resources:
  UIBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: 'jcnix-ui-dev'
  CloudFrontOriginIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: 'origin identity'
  UIBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: 'jcnix-ui-dev'
      PolicyDocument:
        Statement:
          - Sid: 'Allow Jenkins to upload'
            Action:
              - 's3:List*'
              - 's3:Put*'
              - 's3:Delete*'
            Effect: Allow
            Resource: 
              - 'arn:aws:s3:::jcnix-ui-dev'
              - 'arn:aws:s3:::jcnix-ui-dev/*'
            Principal: 
              AWS: 'arn:aws:iam::965128151894:user/jenkins'
          - Sid: 'Allow CloudFront read access'
            Action:
              - 's3:GetObject*'
            Effect: Allow
            Resource:
              - 'arn:aws:s3:::jcnix-ui-dev/*'
            Principal:
              AWS: !Sub 'arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${CloudFrontOriginIdentity}'
    DependsOn:
      - UIBucket
      - CloudFrontOriginIdentity
  UICloudFront:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: jcnix-ui-dev.s3.us-east-1.amazonaws.com
            Id: S3-private-bucket
            S3OriginConfig:
              OriginAccessIdentity: !Sub 'origin-access-identity/cloudfront/${CloudFrontOriginIdentity}'
        Enabled: 'true'
        DefaultRootObject: 'index.html'
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          TargetOriginId: S3-private-bucket
          ForwardedValues:
            QueryString: 'true'
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https
        ViewerCertificate:
          CloudFrontDefaultCertificate: 'true'
        PriceClass: PriceClass_100

  ApiRouteGroup:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: Z07464192VGOEROHHDJUT
      RecordSets:
        - Name: jcnix.com
          Type: A
          AliasTarget:
            HostedZoneId: Z2FDTNDATAQYW2
            DNSName: !GetAtt UICloudFront.DomainName
        - Name: jcnix.com
          Type: AAAA
          AliasTarget:
            HostedZoneId: Z2FDTNDATAQYW2
            DNSName: !GetAtt UICloudFront.DomainName
