Resources:
  UIBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: 'jcnix-ui-dev'
  UIBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: 'jcnix-ui-dev'
      PolicyDocument:
        Statement:
          - Sid: 'Allow Jenkins to upload'
            Action:
              - 's3:List*'
              - 's3:Put*'
              - 's3:Delete*'
            Effect: Allow
            Resource: 
              - 'arn:aws:s3:::jcnix-ui-dev'
              - 'arn:aws:s3:::jcnix-ui-dev/*'
            Principal: 
              AWS: 'arn:aws:iam::965128151894:user/jenkins'
    DependsOn:
      - UIBucket